"""empty message

Revision ID: 6d92d0075744
Revises: 27fd5afc2dfc
Create Date: 2023-08-07 12:44:59.604747

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils as su


# revision identifiers, used by Alembic.
revision = '6d92d0075744'
down_revision = '27fd5afc2dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('reminder')

    # ### end Alembic commands ###
