"""empty message

Revision ID: 8e0bf3aa991b
Revises: 6d92d0075744
Create Date: 2023-08-07 12:57:32.739859

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils as su


# revision identifiers, used by Alembic.
revision = '8e0bf3aa991b'
down_revision = '6d92d0075744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('color', sa.String(length=150), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_label_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_label_id'))

    op.drop_table('label')
    # ### end Alembic commands ###
